server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/last_score?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
    #mapper-locations: classpath*:mapper/**/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    #typeAliasesPackage: com.czxy.score.entity.*